# Generated by Django 2.2.24 on 2022-03-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20220318_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_apartments',
            field=models.ManyToManyField(related_name='owners', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
