# Generated by Django 2.2.24 on 2022-03-18 19:19

from django.db import migrations


def fill_owner_apartments(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.all().iterator():
        flats = Flat.objects.filter(owner=owner.owner, owner_pure_phone=owner.owner_pure_phone)
        if flats:
            owner.owner_apartments.set(flats)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0012_auto_20220318_2135'),
    ]

    operations = [
        migrations.RunPython(fill_owner_apartments)
    ]
