# Generated by Django 2.2.24 on 2022-04-15 18:22

from django.db import migrations


def delete_owner_from_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        flat.owner = ''
        flat.owners_phonenumber = ''
        flat.owner_pure_phone = ''
        flat.save()



class Migration(migrations.Migration):
    dependencies = [
        ('property', '0014_auto_20220415_2110'),
    ]

    operations = [
        migrations.RunPython(delete_owner_from_flat)
    ]
