# Generated by Django 2.2.24 on 2022-04-18 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20220418_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='flats', to=settings.AUTH_USER_MODEL),
        ),
    ]
