# Generated by Django 2.2.24 on 2022-04-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20220418_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_text',
            field=models.TextField(verbose_name='Текст жалобы'),
        ),
    ]
